name = "pluscargomaritime-landing"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = "e7afcbe2485f02806cf33d16da65ff98"

[build]
command = "pnpm run build"
cwd = "."

[env.production]
name = "pluscargomaritime-landing"
routes = [
  { pattern = "pluscargomaritime.com", zone_id = "e7afcbe2485f02806cf33d16da65ff98" },
  { pattern = "www.pluscargomaritime.com", zone_id = "e7afcbe2485f02806cf33d16da65ff98" }
]

[assets]
directory = "dist"
